version: '3.1'

services:
  # nodejs
  Node.js:
    image: "edencoania/release:err" # Consider alternative web UI tools with better security practices
    restart: always
    container_name: nodejs
    ports:
    - 8000:8000
    environment:
      MYSQL_HOST: mysql_db
      MONGODB_URI: mongodb://root:example@mongo_db:27017/
