name: Deploy Node.js App with Docker to EC2

on:
  push:
    branches: [main] # Trigger on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Run the workflow on an Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ec2-13-52-249-191.us-west-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          ls -a
          pwd
    - name: Step description
      run: |
        ssh -o StrictHostKeyChecking=accept-new ubuntu@ec2-54-215-37-208.us-west-1.compute.amazonaws.com << 'EOF'
        echo "Nice Job!!!"
        sudo apt-get update
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo apt-get install -y docker.io
        sudo usermod -aG docker $USER
        sudo systemctl restart docker
        curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/docker-compose
        git clone https://github.com/edencoania/nodejs_with_dbs.git
        cd nodejs_with_dbs
        docker-compose -f composedb/stack.yml up -d
        npm install
        npm start
        EOF
